version: "3.8"
services:
  database:
    image: postgres:15-alpine
    env_file: .env
    ports:
      -5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./server/src/db/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./server/src/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  api:
    build: ./server
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
      NODE_ENV: development
      PORT: 80
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./server/src:/code/src
    command: npm run dev
  app:
    build: ./travelers-compendium
    environment:
      API_URL: http://api
      PORT: ${CLIENT_PORT}
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - api
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - .client/src:/code/src
    command: npm run dev
volumes:
  pg-data: